# Generated by Django 5.2.5 on 2025-09-12 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
